### ISSUE TITLE
connect ENOENT /tmp/.ipchannel

### ISSUE THREAD

**Issue by mapi33** [hyurl/cluster-events#1]
Hi,

I'd love to use the package in production. However I have the following error everytime I reload PM2:

`
3|sandbox  | Error: connect ENOENT /tmp/.ipchannel/122
3|sandbox  |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

2|sandbox  | Error: connect ENOENT /tmp/.ipchannel/122
2|sandbox  |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
PM2        | App name:sandbox id:3 disconnected
PM2        | App [sandbox:3] exited with code [0] via signal [SIGINT]
`

A few things:
- I use PM2 in docker with an Alpine distribution.
- If I restart the docker, it works as expected (until I reload, or if a file changes and is detected by the watch)

Thansk for your help

**Comment by mmelnic** [comment]
@mapi33 
have you figured out the problem? 
or moved to another lib?
